MusicShaper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views

urlpatterns = [
    path('', views.index, name='index'),

    path('admin/', include([
        path('', views.admin_home, name='admin_home'),
        path('django/', admin.site.urls),
        path('create_test_track', views.create_test_track, name='create_test_track'),
        path('claimed_tracks', views.claimed_tracks, name='claimed_tracks'),
    ])),

    path('register/', views.register_page, name='register'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),

    path('profile/', include([
        path('', views.profile_page, {'username': None}, name='profile'),
        path('edit/', views.profile_edit_page, name='profile_edit'),
        path('delete_avatar/', views.delete_avatar, name='delete_avatar'),
        path('change_password/', views.change_password, name='change_password'),
        path('subscriptions/', views.subscriptions_page, name='subscriptions'),
        path('<str:username>/', include([
            path('', views.profile_page, name='profile'),
            path('sub', views.subscribe, name='subscribe'),
            path('unsub', views.unsubscribe, name='unsubscribe'),
        ])),
    ])),

    path('projects/', include([
        path('', views.projects_list, name='projects'),
        path('new/', views.new_project, name='new_project'),
        path('<int:proj_id>/', include([
            path('', views.project_home, name='project_home'),
            path('manage/', views.manage_project, name='manage_project'),
            path('delete/', views.delete_project, name='delete_project'),

            path('instruments/', include([
                path('', views.instruments, name='instruments'),
                path('new/', views.new_instrument, name='new_instrument'),
                path('get/', views.get_instrument_ajax, name='get_instrument'),
                path('<int:instr_id>/', include([
                    path('', views.edit_instrument, name='edit_instrument'),
                    path('manage/', views.manage_instrument, name='manage_instrument'),
                    path('delete/', views.delete_instrument, name='delete_instrument'),
                ])),
            ])),

            path('patterns/', include([
                path('', views.patterns_list, name='patterns'),
                path('new/', views.new_pattern, name='new_pattern'),
                path('<int:pat_id>/', include([
                    path('', views.pattern_editor, name='pattern_editor'),
                    path('manage/', views.manage_pattern, name='manage_pattern'),
                    path('delete/', views.delete_pattern, name='delete_pattern'),
                    path('save/', views.save_pattern, name='save_pattern'),
                ])),
            ])),

            path('timeline/', include([
                path('', views.project_timeline, name='timeline'),
                path('save/', views.save_timeline, name='save_timeline'),
            ])),

            path('upload', views.upload_track, name='upload_track'),
        ])),
    ])),

    path('tracks/', include([
        path('', views.popular_tracks, name='popular_tracks'),
        path('<int:track_id>/', include([
            path('', views.track_view, name='track'),
            path('listen/', views.listen_track, name='listen_track'),
            path('manage/', views.manage_track, name='manage_track'),
            path('claim/', views.claim_track, name='claim_track'),
            path('delete/', views.delete_track, name='delete_track'),
        ])),
    ])),

    path('search/', views.search_page, name='search'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models/music_track.py
'''
=====================================
Модуль моделей для музыкальных треков
=====================================
'''

from django.db import models
from django.forms.models import model_to_dict
from django.contrib.auth.models import User


class TrackComment(models.Model):
    '''
    **Модель Комментария / жалобы**

    :param author: автор
    :param topic: тема
    :param content: содержание
    :param creation_date: дата создания
    :param edit_date: дата редактирования
    :param checked_by_author: просмотрен ли автором трека
    '''

    author = models.ForeignKey(User, models.CASCADE, 'comments')
    topic = models.CharField(max_length=50)
    content = models.CharField(max_length=400)
    creation_date = models.DateTimeField()
    edit_date = models.DateTimeField()


class MusicTrack(models.Model):
    '''
    **Модель опубликованного проекта**

    :param name: имя проекта
    :param desc: описание
    :param author: автор
    :param creation_date: дата публикации
    :param likes: список юзеров, поставивших лайк
    :param dislikes: список юзеров, поставивших дизлайк
    :param comments: список комментариев
    :param claims: список жалоб
    :param settings: настройки
    :param listeners: список юзеров, послушавших трек
    '''

    name = models.CharField(max_length=50)
    desc = models.CharField(max_length=250)
    author = models.ForeignKey(User, models.CASCADE, 'tracks')
    creation_date = models.DateTimeField()
    audio_file = models.FileField(upload_to='music_tracks/', blank=True)

    likes = models.ManyToManyField(User, 'likes')
    dislikes = models.ManyToManyField(User, 'dislikes')
    comments = models.ManyToManyField(TrackComment, 'comments')
    claims = models.ManyToManyField(TrackComment, 'claims')
    listeners = models.ManyToManyField(User, 'listened_tracks')

    def to_dict(self):
        '''
        Переводит модель трека в словарь
        (ManyToMany поля недоступны, ForeignKey заменены на id)

        :rtype: dict
        '''

        return model_to_dict(self, fields=(
            'id', 'name', 'desc', 'author', 'creation_date', 'settings'
        ))


class TrackSettings(models.Model):
    '''
    **Настройки публикации проекта**

    :param track: музыкальный трек
    :param access: уровень доступа к треку
    :param allow_comments: разрешены ли комментарии
    :param allow_rating: разрешены ли лайки / дизлайки
    :param allow_reusing: разрешено ли свободное использование
    '''

    track = models.OneToOneField(
        MusicTrack, models.CASCADE,
        primary_key=True, related_name='settings'
    )

    ACCESS_CHOICES = [
        (0, 'private'),
        (1, 'link'),
        (2, 'public'),
    ]

    access = models.PositiveIntegerField(choices=ACCESS_CHOICES)

    allow_comments = models.BooleanField()
    allow_rating = models.BooleanField()
    allow_reusing = models.BooleanField()

main/views/admin.py
'''
===============================================
Модуль view-функций для вкладки `Администрация`
===============================================
'''

from datetime import datetime
from django.shortcuts import render, redirect
from django.contrib.messages import add_message, SUCCESS, ERROR
from django.contrib.auth.decorators import user_passes_test, login_required
from .util import get_base_context
from ..forms import CreateTestTrack
from ..models import MusicTrack, TrackSettings


superuser_check = lambda u: u.is_superuser


@login_required
@user_passes_test(superuser_check)
def admin_home(request):
    '''
    **Панель администрации**

    :param request: запрос клиента
    :rtype: HttpResponse
    '''

    return render(request, 'admin/admin.html', get_base_context(request))


@login_required
@user_passes_test(superuser_check)
def create_test_track(request):
    '''
    **Страница создания пробного трека**

    :param request: запрос клиента
    :return: страница создания пробного трека
    :rtype: HttpResponse
    '''

    if request.method == 'POST':
        form = CreateTestTrack(request.POST)
        if form.is_valid():
            track = MusicTrack.objects.create(
                name=form.data['name'],
                desc=form.data['desc'],
                author=request.user,
                creation_date=datetime.now(),
            )
            TrackSettings.objects.create(
                track=track,
                access=2,
                allow_rating=form.data.get('allow_rating', 'off') == 'on',
                allow_reusing=form.data.get('allow_reusing', 'off') == 'on',
                allow_comments=form.data.get('allow_comments', 'off') == 'on',
            )
            add_message(request, SUCCESS, 'Трек успешно создан')
            return redirect('track', track_id=track.id)
        add_message(request, ERROR, 'Некорректные данные формы')
    else:
        form = CreateTestTrack()

    context = get_base_context(request, {
        'form': form
    })

    return render(request, 'admin/create_test_track.html', context)


@login_required
@user_passes_test(superuser_check)
def claimed_tracks(request):
    '''
    Страница жалоб

    :param request: запрос клиента
    :return: страница трека с жалобой
    :rtype: HttpResponse
    '''
    context = get_base_context(request)

    all_tracks = MusicTrack.objects.filter(settings__access__gt=0).all()
    context["tracks"] = [{"name": t.name, "id": t.id, "count": t.claims.count()}
                         for t in all_tracks]
    context["tracks"].sort(key=lambda i: i["count"], reverse=True)
    context["tracks"] = filter(lambda t: t["count"] > 0, context["tracks"])

    return render(request, 'admin/claimed_tracks.html', context)

main/views/claim_track.py
'''
Модуль жалоб на музыкальные треки
'''

from datetime import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest
from django.contrib.messages import add_message, SUCCESS, ERROR
from django.contrib.auth.decorators import login_required

from .util import get_base_context
from ..models import MusicTrack, TrackComment
from ..forms import ClaimForm


@login_required
def claim_track(request: HttpRequest, track_id: int):
    '''
    Страница создания / редактирования жалобы на трек

    :param request: запрос клиента
    :param track_id: id трека в БД
    :rtype: HttpResponse
    '''

    context = get_base_context(request)

    track = get_object_or_404(MusicTrack, pk=track_id)
    context['track'] = track

    if request.user == track.author:
        add_message(request, ERROR, 'Вы не можете создать жалобу на свой трек!')
        return redirect('track', track_id=track_id)

    old_claim = track.claims.filter(author=request.user).first()
    context['old_claim'] = old_claim

    if request.method == 'POST':
        form = ClaimForm(request.POST)
        if form.is_valid():
            if old_claim:
                if old_claim.content == form.data['content']\
                and old_claim.topic == form.data['topic']:
                    add_message(request, ERROR, 'Ничего не изменено')
                    return redirect('track', track_id=track_id)

                old_claim.topic = form.data['topic']
                old_claim.content = form.data['content']
                old_claim.save()
                add_message(request, SUCCESS, 'Жалоба успешно отредактирована')
            else:
                new_claim = TrackComment.objects.create(
                    author=request.user,
                    topic=form.data['topic'],
                    content=form.data['content'],
                    creation_date=datetime.now(),
                    edit_date=datetime.now(),
                )
                track.claims.add(new_claim)
                add_message(request, SUCCESS, 'Жалоба успешно создана')
            return redirect('track', track_id=track_id)

        add_message(request, ERROR, 'Некорректные данные формы')
        context['claimform'] = form
    else:
        context['claimform'] = ClaimForm(data={
            'topic': old_claim.topic if old_claim else '',
            'content': old_claim.content if old_claim else ''
        })

    return render(request, 'track/claim_track.html', context)

main/views/instrument.py
'''
================================================
Модуль view-функций для музыкальных инструментов
================================================
'''

from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.messages import add_message, SUCCESS, ERROR
from .util import get_base_context, ajax_view
from ..forms import MusicInstrumentForm, SettingsModelForm
from .project import get_project_or_404
from ..models import MusicInstrument


@login_required
def instruments(request, proj_id: int):
    '''
    **Страница со списком всех музыкальных инструментов
    в проекте**

    :param request: запрос клиента
    :param proj_id: id проекта в базе данных
    :return: список инструментов
    :rtype: HttpResponse
    '''

    project = get_project_or_404(request, proj_id)

    context = get_base_context(request, {
        'project': project,
        'instruments': project.instruments
    })

    return render(request, 'instrument/list.html', context)


@login_required
def new_instrument(request, proj_id: int):
    '''
    **Страница создания музыкального инструмента**

    :param request: запрос клиента
    :param proj_id: id проекта в базе данных
    :return: страница создания инструмента
    :rtype: HttpResponse
    '''

    project = get_project_or_404(request, proj_id)

    if request.method == 'POST':
        form = MusicInstrumentForm(project, data=request.POST)
        if form.is_valid():
            try:
                existed_i = MusicInstrument.objects.filter(
                    project=project, name=form.data['name']
                )
                if existed_i:
                    raise LookupError

                instrument = form.save()
            except TypeError:
                add_message(request, ERROR, 'Неизвестный тип инструмента')
            except LookupError:
                add_message(
                    request, ERROR, 'Инструмент с таким именем уже существует'
                )
            else:
                add_message(request, SUCCESS, 'Инструмент успешно создан')
                return redirect('edit_instrument', proj_id=proj_id, instr_id=instrument.id)
        else:
            add_message(request, ERROR, 'Некорректные данные формы')
    else:
        form = MusicInstrumentForm(project)

    context = get_base_context(request, {
        'project': project,
        'form': form
    })

    return render(request, 'instrument/new.html', context)


@login_required
def edit_instrument(request, proj_id: int, instr_id: int):
    '''
    **Страница редактирования настроек инструмента**

    :param request: запрос клиента
    :param proj_id: id проекта в БД
    :param instr_id: id инстуремнта в БД
    '''

    project = get_project_or_404(request, proj_id)
    instrument = get_object_or_404(MusicInstrument, pk=instr_id)

    if request.method == 'POST':
        form = SettingsModelForm(instance=instrument, data=request.POST)
        if form.is_valid():
            instrument = form.save()
            add_message(request, SUCCESS, 'Изменения успешно сохранены')
        else:
            add_message(request, ERROR, 'Некорректные данные формы')
    else:
        form = SettingsModelForm(instance=instrument)

    context = get_base_context(request, {
        'project': project,
        'instrument': instrument,
        'form': form,
    })

    return render(request, 'instrument/edit.html', context)


@login_required
def manage_instrument(request, proj_id: int, instr_id: int):
    '''
    **Страница управления инструментом**

    :param request: запрос клиента
    :param proj_id: id проекта в БД
    :param instr_id: id инстуремнта в БД
    '''

    project = get_project_or_404(request, proj_id)
    instrument = get_object_or_404(MusicInstrument, pk=instr_id)

    if request.method == 'POST':
        form = MusicInstrumentForm(project, instance=instrument, data=request.POST)
        if form.is_valid():
            form.save()
            add_message(request, SUCCESS, 'Изменения успешно сохранены')
            return redirect('edit_instrument', proj_id=proj_id, instr_id=instr_id)
        add_message(request, ERROR, 'Некорректные данные формы')
    else:
        form = MusicInstrumentForm(project, instance=instrument)

    context = get_base_context(request, {
        'project': project,
        'instrument': instrument,
        'form': form,
    })

    return render(request, 'instrument/manage.html', context)


@login_required
def delete_instrument(request, proj_id: int, instr_id: int):
    '''
    **Страница удаления инструмента**

    :param request: запрос клиента
    :param proj_id: id проекта в БД
    :param instr_id: id инстуремнта в БД
    '''

    project = get_project_or_404(request, proj_id)
    instrument = get_object_or_404(MusicInstrument, pk=instr_id)

    if request.method == 'POST':
        instrument.delete()
        add_message(request, SUCCESS, 'Инструмент успешно удалён')
        return redirect('instruments', proj_id=proj_id)

    context = get_base_context(request, {
        'project': project,
        'title': 'Удаление инструмента',
        'item_name': instrument.name,
        'confirm_title': 'Удалить инструмент',
        'cancel_title': 'Назад к настройкам',
        'cancel_url': reverse('manage_instrument', kwargs={
            'proj_id': project.pk,
            'instr_id': instrument.pk
        })
    })

    return render(request, 'delete.html', context)


@login_required
@ajax_view(method='GET', required_args=('name',))
def get_instrument_ajax(request, proj_id: int):
    '''
    Возвращает клиенту настройки инструмента через ajax
    '''

    project = get_project_or_404(request, proj_id)
    i_name = request.GET['name']

    return {
        i_name: MusicInstrument.objects.get(project=project, name=i_name).to_dict()
    }

main/templates/track/claim_track.html
{% extends 'base.html' %}

{% block 'title' %}
    {% if old_claim %}Редактирование{% else %}Создание{% endif %} жалобы
{% endblock %}

{% block 'body' %}
    <div class="margin-top-20"></div>
    <div class="text-center">
        <h2>
            {% if old_claim %}Редактирование{% else %}Создание{% endif %} жалобы
        </h2>
        <a href="{% url 'track' track_id=track.id %}">
            Назад к треку
        </a>
    </div>
    <br>
    <form method="POST">
        {% csrf_token %}
        {% for field in claimform.visible_fields %}
            <div class="form-group">
                <label>{{ field.label }}: </label>
                {{ field }}
            </div>
        {% endfor %}
        <br>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Отправить жалобу</button>
        </div>
    </form>
{% endblock %}

main/templates/track/manage.html
{% extends 'base.html' %}

{% block 'title' %}
    Управление треком {{ track.name }}
{% endblock %}

{% block 'body' %}
    <div class="text-center margin-top-20">
        <h2>Управление треком</h2>
        <h3 class="quotes">{{ track.name }}</h3>
        <a href="{% url 'track' track_id=track.id %}">
            Назад к треку
        </a>
    </div>
    <form method="POST" style="max-width: 45%;" class="mx-auto margin-top-2">
        {% csrf_token %}
        {% for field in form.visible_fields %}
            {% if field.field.widget.input_type != 'checkbox' %}
            <div class="form-group">
                <label>{{ field.label }}: </label>
                {{ field }}
                </div>
            {% else %}
                <div class="form-check">
                    {{ field }}
                    <label>{{ field.label }}</label>
                </div>
            {% endif %}
        {% endfor %}
        <div class="text-center">
            <input type="submit" value="Сохранить изменения" class="btn btn-outline-success margin-top-10">
            <div class="margin-top-10"></div>
            <a href="{% url 'delete_track' track_id=track.id %}"
                class="btn btn-outline-danger">
                Удалить трек
            </a>
        </div>
    </form>
{% endblock %}

main/templates/track/view.html
{% extends 'base.html' %}
{% load i18n %}

{% block 'title' %}
    {{ track.name }} - {{ track.author.username }}
{% endblock %}

{% block 'head' %}
    <style>
        button {
            margin-top: 15px;
        }

        #comments {
            width: 80%;
        }

        #sendbtn {
            margin-bottom: 15px;
        }

        #like, #dislike {
            all: unset;
            cursor: pointer;
        }

        .my_comment button {
            display: none;
        }

        .my_comment:hover button {
            display: block;
        }
    </style>
{% endblock %}

{% block 'body' %}
    <h1 class="margin-top-10 text-center">
        {{ track.name }}
    </h1>
    {% if track.desc %}
        <h5 class="text-secondary text-center margin-top-2 quotes">{{ track.desc }}</h5>
    {% endif %}
    <p class="text-center margin-top-2">
        <b>
            Автор:
            <a href="{% url 'profile' username=track.author.username %}">
                {{ track.author }}
            </a>
        </b> <br>
        <b> Дата Создания: </b> {{ track.creation_date|date:"d.m.Y G:i" }} <br>
        Уровень доступа: {% trans track.settings.get_access_display %}
    </p>
    {% if track.settings.allow_rating %}
        <h1 class="text-center margin-top-5" id="rating">
            <button id="like" onclick="like()">👍</button>
            : <b id="likes_counter">{{ track.likes.count }}   </b>
            <button id="dislike" onclick="dislike()">👎</button>
            : <b id="dislikes_counter">{{ track.dislikes.count }}</b>
        </h1>
    {% endif %}

    <br>
    <div class="text-center">
        {% if user == track.author %}
            <a class="btn btn-outline-primary" href="{% url 'manage_track' track_id=track.id %}">
                Управление треком
            </a>
        {% endif %}
        {% if user != track.author and not user.is_superuser %}
            <a class="btn btn-danger" href="{% url 'claim_track' track_id=track.id %}">
                Пожаловаться
            </a>
        {% endif %}
        {% if user.is_superuser and track.claims.count >= 3 %}
            <a href="{% url 'delete_track' track_id=track.id %}"
                class="btn btn-outline-danger">
                Удалить трек
            </a>
        {% endif %}
    </div>

    {% if track.audio_file %}
        <div class="text-center margin-top-5">
            Количество прослушиваний: <span id="listenersCount">{{ track.listeners.count }}</span>
        </div>
        <div style="width: 100%; display: flex; justify-content: center; margin-top: 10px;">
            <audio src="{{ track.audio_file.url }}" id="trackAudio" controls
            {% if not track.settings.allow_reusing %}controlsList="nodownload"{% endif %}>
            </audio>
        </div>
    {% endif %}

    {% if track.claims.exists %}
        {% if user.is_superuser or track.author == user %}
            <div class="margin-top-5"></div>
            <h3 class="text-center">Жалобы:</h3>
            <div>
                {% for t in track.claims.all %}
                    <div class="card" style="margin-bottom: 10px;">
                        <div class="card-body">
                            <h5 class="card-title">Автор: {{ t.author }}</h5>
                            <p><b>{{ t.topic }}</b></p>
                            <p><i>{{ t.content }}</i></p>
                            <small>
                                Дата создания / последнего изменения: {{ t.creation_date|date:"d.m.Y G:i" }}
                            </small>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <br>
        {% endif %}
    {% endif %}

    {% if track.settings.allow_comments %}
        <div style="width: 80%;" class="mx-auto">
            <h3 class="margin-top-5" id="comment_counter">
                Комментарии ({{ track.comments.count }})
                {% if track.comments.count == 0 %}
                    <i class="text-secondary"
                    style="font-size: 0.6em; position: relative; bottom: 0.3em;">
                        &lt;&ndash; Будьте первым!
                    </i>
                {% endif %}
            </h3>
            <label>Напишите ваш комментарий</label>
            <input type="text" id="topic" class="form-control" placeholder="Тема" required>
            <br>
            <textarea id="comm" placeholder="Содержание" required
                      class="form-control" style="min-height: 40px; max-height: 180px;"></textarea>
            <button onclick="send_comment()" class="btn btn-success" id="sendbtn">
                Отправить
            </button>
        </div>
        <div class="list-group mx-auto" id="comments">
            {% for comment in track.comments.all %}
                <div id="comment_{{ comment.id }}"
                     class="list-group-item {% if comment.author == user %}my_comment{% endif %}">
                    <h6>
                        {{ comment.topic }} {{ comment.creation_date|date:"d.m.Y G:i" }}
                    </h6>
                    <p>
                        {{ comment.content }}
                    </p>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

{% block 'scripts' %}
    <script>
        let already_listened = false;
        document.querySelector('#trackAudio').addEventListener('ended', () => {
            if (already_listened) return;
            $.ajax({
                method: 'POST',
                url: "{% url 'listen_track' track_id=track.id %}",
                dataType: 'json',
                data: { csrfmiddlewaretoken: '{{ csrf_token }}' },
                success: (data) => {
                    if (data.success && data.listenersCount) {
                        document.querySelector('#listenersCount').innerText = data.listenersCount;
                        already_listened = true;
                    }
                }
            });
        });

        const comm = document.getElementById('comm');
        const topic = document.getElementById('topic');
        const my_comments = document.querySelectorAll(".my_comment");

        let already_liked = "{{ liked }}" === "True";
        let already_disliked = "{{ disliked }}" === "True";

        if (already_liked && already_disliked) {
            already_liked = false;
            already_disliked = true;
            dislike().then(() => {
                already_disliked = false;
                already_liked = true;
                like();
            });
        }

        update_icons({total_likes: "{{ total_likes }}", total_dislikes: "{{ total_dislikes}}"});

        for (const comment of my_comments) {
            const button = document.createElement("button");
            button.innerHTML = "Отредактировать";
            button.classList.add("btn", "btn-success");
            comment.appendChild(button);
            const d_button = document.createElement("button")
            d_button.innerHTML = "Удалить";
            d_button.classList.add("btn", "btn-danger");
            comment.appendChild(d_button);
            let p = comment.querySelector("p");
            d_button.onclick = () => ajax_promise({
                operation: "delete",
                comment_id: comment.id.replace("comment_", "")
            }).then(() => {
                p.parentNode.remove();
                const comments = document.getElementById("comments");
                const comment_counter = document.querySelector("#comment_counter");
                comment_counter.innerHTML = comment_counter.innerHTML.replace(/\(\d+\)/,
                    `(${comments.childElementCount})`)

            })
            let first_on_click = () => {
                const content = p.innerText;
                comment.removeChild(p);
                const text = document.createElement("textarea");
                text.classList.add("form-control");
                comment.insertBefore(text, button);
                text.value = content;
                button.innerHTML = "Сохранить";
                button.classList.replace("btn-outline-dark", "btn-outline-success");
                button.onclick = () => ajax_promise({
                    operation: "edit",
                    comment: text.value,
                    topic: topic.value,
                    comment_id: comment.id.replace("comment_", "")
                })
                    .then(data => {
                        p = document.createElement("p");
                        p.innerHTML = text.value;
                        comment.removeChild(text);
                        comment.insertBefore(p, button);
                        button.onclick = first_on_click;
                        button.innerHTML = "Отредактировать";
                        button.classList.replace("btn-outline-success", "btn-outline-dark");
                    });
            };
            button.onclick = first_on_click;
        }

        function update_icons(data) {
            if (!document.getElementById("rating")) {
                return
            }
            if (data.total_dislikes !== undefined) {
                document.getElementById('dislikes_counter').innerHTML = data.total_dislikes;
                document.getElementById('dislike').innerHTML = already_disliked ? "🤢" : "👎";
            }
            if (data.total_likes !== undefined) {
                document.getElementById('likes_counter').innerHTML = data.total_likes;
                document.getElementById('like').innerHTML = already_liked ? "😍" : "👍";
            }
        }

        function ajax_promise(data) {
            return new Promise((resolve, reject) => {
                $.ajax({
                    url: location.href,
                    dataType: "json",
                    data: {
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        ...data
                    },
                    success: (data) => {
                        if (data.success) resolve(data);
                        else reject('failed');
                    },
                    error: (xhr, status, err) => {
                        reject(err);
                    }
                });
            })
        }

        async function like() {
            if (already_disliked) await dislike();
            try {
                const data = await ajax_promise({operation: 'like'});
                already_liked = !already_liked;
                update_icons(data);
            } catch (err) {
                console.error('failed to like');
                console.error(err);
            }
        }

        async function dislike() {
            if (already_liked) await like();
            try {
                const data = await ajax_promise({operation: 'dislike'});
                already_disliked = !already_disliked;
                update_icons(data);
            } catch (err) {
                console.error('failed to dislike');
                console.error(err);
            }
        }

        function send_comment() {
            if (comm.value === '' || topic.value === '') {
                alert('Пожалуйста, заполните поля');
                return;
            }
            ajax_promise({
                operation: 'send',
                comment: comm.value,
                topic: topic.value,
            }).then(() => location.reload());
        }

    </script>
{% endblock %}